import type { Meal } from './types';

export const meals: Meal[] = [
  // ─── BREAKFAST ────────────────────────────────────────────────────────────
  {
    id: 'b1',
    name: 'Scrambled Eggs with Spinach & Tomatoes',
    type: 'breakfast',
    description: 'Fluffy scrambled eggs loaded with fresh spinach and cherry tomatoes — a protein-rich start to your day.',
    calories: 320,
    protein: 22,
    carbs: 8,
    fat: 22,
    fiber: 2,
    ingredients: ['3 large eggs', '1 cup baby spinach', '½ cup cherry tomatoes', '1 tbsp olive oil', 'Salt & pepper', 'Fresh chives'],
    preparation: 'Whisk eggs with a pinch of salt. Heat olive oil in a non-stick pan, sauté tomatoes 1 min, add spinach until wilted, then pour in eggs and fold gently until just set. Top with chives.',
    excludeFor: [],
  },
  {
    id: 'b2',
    name: 'Greek Yogurt Parfait with Berries',
    type: 'breakfast',
    description: 'Creamy Greek yogurt layered with mixed berries and a drizzle of honey for natural sweetness.',
    calories: 280,
    protein: 18,
    carbs: 32,
    fat: 6,
    fiber: 4,
    ingredients: ['200g Greek yogurt (full-fat)', '½ cup mixed berries', '1 tbsp honey', '1 tbsp chia seeds', 'Fresh mint'],
    preparation: 'Layer yogurt in a bowl or glass, top with berries, sprinkle chia seeds, drizzle honey and garnish with mint.',
    excludeFor: ['vegan', 'dairy_free'],
  },
  {
    id: 'b3',
    name: 'Avocado & Poached Egg Bowl',
    type: 'breakfast',
    description: 'Halved avocado topped with a perfectly poached egg — creamy, satisfying and full of healthy fats.',
    calories: 350,
    protein: 14,
    carbs: 10,
    fat: 28,
    fiber: 7,
    ingredients: ['1 ripe avocado', '2 eggs', '½ lemon', 'Red pepper flakes', 'Salt & pepper', '1 tsp white vinegar'],
    preparation: 'Bring water to a gentle simmer, add vinegar. Crack each egg into a cup and slide in. Poach 3 min. Halve avocado, season with lemon, salt and pepper flakes, top with eggs.',
    excludeFor: ['vegan'],
  },
  {
    id: 'b4',
    name: 'Chia Seed Pudding with Mango',
    type: 'breakfast',
    description: 'Make-ahead chia pudding with luscious mango and toasted coconut — vibrant and refreshing.',
    calories: 290,
    protein: 8,
    carbs: 36,
    fat: 12,
    fiber: 11,
    ingredients: ['3 tbsp chia seeds', '1 cup coconut milk', '1 ripe mango, diced', '1 tbsp shredded coconut', '1 tsp vanilla extract', '1 tsp maple syrup'],
    preparation: 'Mix chia seeds with coconut milk, vanilla and maple syrup. Refrigerate overnight (min 4 h). Top with fresh mango and toasted coconut.',
    excludeFor: ['nut_free'],
  },
  {
    id: 'b5',
    name: 'Spinach & Feta Frittata',
    type: 'breakfast',
    description: 'Oven-baked egg frittata packed with spinach, feta and herbs — ideal for meal prep.',
    calories: 360,
    protein: 26,
    carbs: 6,
    fat: 26,
    fiber: 1,
    ingredients: ['4 eggs', '100g feta cheese', '2 cups spinach', '¼ red onion, sliced', '1 tbsp olive oil', 'Dried oregano', 'Salt & pepper'],
    preparation: 'Preheat oven to 180 °C. Sauté onion in oven-safe skillet, add spinach until wilted. Pour whisked eggs over, crumble feta on top, season and bake 15 min until set.',
    excludeFor: ['vegan', 'dairy_free'],
  },
  {
    id: 'b6',
    name: 'Smoked Salmon & Cucumber Rolls',
    type: 'breakfast',
    description: 'Thin cucumber ribbons wrapped around cream cheese and smoked salmon — elegant and light.',
    calories: 240,
    protein: 20,
    carbs: 5,
    fat: 15,
    fiber: 1,
    ingredients: ['100g smoked salmon', '60g cream cheese', '1 large cucumber', '1 tbsp capers', 'Fresh dill', 'Lemon zest'],
    preparation: 'Use a peeler to make long cucumber ribbons. Spread cream cheese on each ribbon, place salmon, capers and dill, then roll up and secure with a toothpick.',
    excludeFor: ['vegetarian', 'vegan', 'dairy_free'],
  },
  {
    id: 'b7',
    name: 'Cottage Cheese Bowl with Peaches & Almonds',
    type: 'breakfast',
    description: 'Creamy cottage cheese with sliced peaches and crunchy almonds — high protein and satisfying.',
    calories: 310,
    protein: 28,
    carbs: 22,
    fat: 10,
    fiber: 2,
    ingredients: ['200g cottage cheese', '1 ripe peach, sliced', '20g sliced almonds', '1 tsp honey', 'Cinnamon'],
    preparation: 'Spoon cottage cheese into a bowl. Arrange peach slices, scatter almonds, drizzle honey and dust with cinnamon.',
    excludeFor: ['vegan', 'dairy_free', 'nut_free'],
  },
  {
    id: 'b8',
    name: 'Vegetable Omelette with Goat Cheese',
    type: 'breakfast',
    description: 'Three-egg omelette stuffed with colourful peppers, mushrooms and tangy goat cheese.',
    calories: 380,
    protein: 28,
    carbs: 9,
    fat: 26,
    fiber: 2,
    ingredients: ['3 eggs', '50g goat cheese', '½ bell pepper, diced', '4 mushrooms, sliced', '¼ cup onion, diced', '1 tbsp butter', 'Chives', 'Salt & pepper'],
    preparation: 'Sauté vegetables in butter 3 min. Whisk eggs, pour into pan over vegetables. When edges set, crumble goat cheese on half, fold over and slide onto plate.',
    excludeFor: ['vegan', 'dairy_free'],
  },
  {
    id: 'b9',
    name: 'Green Protein Smoothie Bowl',
    type: 'breakfast',
    description: 'Thick blended smoothie of banana, spinach and almond butter, topped with seeds and coconut.',
    calories: 340,
    protein: 14,
    carbs: 38,
    fat: 16,
    fiber: 7,
    ingredients: ['1 frozen banana', '2 cups spinach', '2 tbsp almond butter', '1 cup almond milk', '1 tbsp hemp seeds', '1 tbsp pumpkin seeds', '2 tbsp shredded coconut'],
    preparation: 'Blend banana, spinach, almond butter and almond milk until thick and smooth. Pour into a bowl and top with seeds and coconut.',
    excludeFor: ['nut_free'],
  },
  {
    id: 'b10',
    name: 'Turkey & Vegetable Egg Cups',
    type: 'breakfast',
    description: 'Oven-baked egg cups lined with turkey slices, filled with vegetables — portable and protein-packed.',
    calories: 290,
    protein: 30,
    carbs: 5,
    fat: 16,
    fiber: 1,
    ingredients: ['4 thin-sliced turkey breast', '4 eggs', '½ cup diced bell peppers', '½ cup baby spinach', '2 tbsp salsa', 'Salt & pepper'],
    preparation: 'Preheat oven 180 °C. Line muffin tins with turkey slices, add a spoonful of veggies and salsa, crack an egg over each. Season and bake 15–18 min until set.',
    excludeFor: ['vegetarian', 'vegan'],
  },
  {
    id: 'b11',
    name: 'Quinoa Breakfast Bowl with Berries',
    type: 'breakfast',
    description: 'Warm quinoa porridge with almond milk, cinnamon and fresh berries — a hearty grain-free alternative.',
    calories: 360,
    protein: 12,
    carbs: 52,
    fat: 9,
    fiber: 6,
    ingredients: ['½ cup quinoa', '1 cup almond milk', '½ cup mixed berries', '1 tbsp maple syrup', '½ tsp cinnamon', '1 tbsp pumpkin seeds'],
    preparation: 'Cook quinoa in almond milk with cinnamon over medium heat ~15 min until creamy. Top with berries, seeds and maple syrup.',
    excludeFor: ['no_bread', 'low_carb'],
  },
  {
    id: 'b12',
    name: 'Baked Egg & Tomato Shakshuka',
    type: 'breakfast',
    description: 'Eggs poached in a spiced tomato and pepper sauce — a North African classic bursting with flavour.',
    calories: 300,
    protein: 16,
    carbs: 20,
    fat: 16,
    fiber: 5,
    ingredients: ['3 eggs', '400g crushed tomatoes', '1 red pepper', '1 onion', '2 garlic cloves', '1 tsp cumin', '1 tsp paprika', '½ tsp cayenne', '2 tbsp olive oil', 'Fresh parsley'],
    preparation: 'Sauté onion and pepper 5 min, add garlic and spices. Pour in tomatoes, simmer 10 min. Make wells, crack eggs in, cover and cook 6–8 min until whites are set.',
    excludeFor: ['vegan'],
  },

  // ─── LUNCH ────────────────────────────────────────────────────────────────
  {
    id: 'l1',
    name: 'Grilled Chicken Caesar Salad',
    type: 'lunch',
    description: 'Juicy grilled chicken strips over crispy romaine with a light Caesar dressing and parmesan.',
    calories: 420,
    protein: 40,
    carbs: 8,
    fat: 24,
    fiber: 3,
    ingredients: ['150g chicken breast', '2 cups romaine lettuce', '30g parmesan', '2 tbsp Caesar dressing', 'Lemon juice', 'Black pepper', '1 tbsp olive oil'],
    preparation: 'Season chicken with salt, pepper and lemon juice. Grill 6 min per side. Slice and toss with romaine, parmesan and dressing.',
    excludeFor: ['vegetarian', 'vegan'],
  },
  {
    id: 'l2',
    name: 'Tuna & Avocado Salad',
    type: 'lunch',
    description: 'Chunky tuna mixed with ripe avocado, cucumber and lime — satisfying without any grains.',
    calories: 370,
    protein: 32,
    carbs: 12,
    fat: 22,
    fiber: 6,
    ingredients: ['150g canned tuna (in water)', '1 avocado', '½ cucumber, diced', '½ red onion, diced', '1 lime', '1 tbsp olive oil', 'Fresh cilantro', 'Salt & pepper'],
    preparation: 'Drain tuna. Mash avocado with lime juice. Fold in tuna, cucumber and onion. Season and garnish with cilantro.',
    excludeFor: ['vegetarian', 'vegan'],
  },
  {
    id: 'l3',
    name: 'Red Lentil Soup',
    type: 'lunch',
    description: 'Hearty red lentil soup with cumin and turmeric — warming, filling and naturally plant-based.',
    calories: 320,
    protein: 18,
    carbs: 48,
    fat: 6,
    fiber: 14,
    ingredients: ['1 cup red lentils', '1 onion', '2 carrots', '2 garlic cloves', '1 tsp cumin', '1 tsp turmeric', '1 litre vegetable stock', '2 tbsp olive oil', 'Lemon juice', 'Fresh parsley'],
    preparation: 'Sauté onion, carrot and garlic 5 min. Add lentils, spices and stock, simmer 20 min. Blend half the soup for a creamy texture. Finish with lemon juice and parsley.',
    excludeFor: ['low_carb'],
  },
  {
    id: 'l4',
    name: 'Turkey Lettuce Wraps',
    type: 'lunch',
    description: 'Seasoned ground turkey in crisp butter lettuce cups with hoisin and sesame — light and fun.',
    calories: 350,
    protein: 34,
    carbs: 14,
    fat: 16,
    fiber: 3,
    ingredients: ['200g ground turkey', '8 butter lettuce leaves', '1 tbsp hoisin sauce', '1 tbsp soy sauce (or tamari)', '1 tsp sesame oil', '1 carrot, shredded', '2 spring onions', '1 tsp ginger, grated', '1 garlic clove'],
    preparation: 'Brown turkey with garlic and ginger. Add sauces and sesame oil, cook 2 min. Serve in lettuce cups, top with carrot and spring onion.',
    excludeFor: ['vegetarian', 'vegan'],
  },
  {
    id: 'l5',
    name: 'Greek Salad with Grilled Halloumi',
    type: 'lunch',
    description: 'Classic Greek salad with juicy tomatoes, kalamata olives and salty grilled halloumi slices.',
    calories: 400,
    protein: 20,
    carbs: 14,
    fat: 28,
    fiber: 4,
    ingredients: ['150g halloumi', '2 tomatoes', '½ cucumber', '½ red onion', '80g kalamata olives', '2 tbsp olive oil', '1 tbsp red wine vinegar', 'Dried oregano'],
    preparation: 'Grill halloumi slices 2 min per side until golden. Chop vegetables, combine with olives. Dress with oil, vinegar and oregano. Top with halloumi.',
    excludeFor: ['vegan', 'dairy_free'],
  },
  {
    id: 'l6',
    name: 'Zucchini Noodles with Pesto & Cherry Tomatoes',
    type: 'lunch',
    description: 'Spiralised zucchini tossed in basil pesto with burst cherry tomatoes and pine nuts.',
    calories: 300,
    protein: 8,
    carbs: 16,
    fat: 22,
    fiber: 4,
    ingredients: ['2 medium zucchini', '3 tbsp basil pesto', '1 cup cherry tomatoes', '2 tbsp pine nuts', 'Parmesan (optional)', 'Salt & pepper'],
    preparation: 'Spiralise zucchini. Halve and pan-roast tomatoes 3 min until blistered. Toss noodles with pesto (no heat needed). Top with tomatoes and pine nuts.',
    excludeFor: ['nut_free', 'low_carb'],
  },
  {
    id: 'l7',
    name: 'Smoked Salmon & Cucumber Bites',
    type: 'lunch',
    description: 'Thick cucumber rounds topped with herbed cream cheese and smoked salmon — zero grains required.',
    calories: 250,
    protein: 22,
    carbs: 6,
    fat: 15,
    fiber: 1,
    ingredients: ['100g smoked salmon', '80g cream cheese', '1 large cucumber', '1 tbsp capers', 'Fresh dill', 'Lemon zest', 'Black pepper'],
    preparation: 'Slice cucumber into thick rounds. Mix cream cheese with dill and lemon zest. Pipe or spread onto cucumber, top with salmon and capers.',
    excludeFor: ['vegetarian', 'vegan', 'dairy_free'],
  },
  {
    id: 'l8',
    name: 'Chicken & Vegetable Stir-Fry',
    type: 'lunch',
    description: 'Tender chicken with crisp broccoli, peppers and snap peas in a ginger-soy sauce.',
    calories: 380,
    protein: 38,
    carbs: 20,
    fat: 14,
    fiber: 5,
    ingredients: ['150g chicken breast, sliced', '1 cup broccoli florets', '1 bell pepper', '1 cup snap peas', '2 tbsp soy sauce (or tamari)', '1 tsp sesame oil', '1 tbsp oyster sauce', '1 tsp ginger', '1 garlic clove', '1 tbsp olive oil'],
    preparation: 'Stir-fry chicken in hot oil 4 min. Remove. Stir-fry vegetables 3 min. Return chicken, add sauces, ginger and garlic. Toss to coat and serve.',
    excludeFor: ['vegetarian', 'vegan'],
  },
  {
    id: 'l9',
    name: 'Mediterranean Chickpea Salad',
    type: 'lunch',
    description: 'Chickpeas with roasted peppers, cucumber, olives and fresh herbs in a lemon-oregano dressing.',
    calories: 340,
    protein: 14,
    carbs: 42,
    fat: 12,
    fiber: 12,
    ingredients: ['400g canned chickpeas', '1 roasted red pepper', '½ cucumber, diced', '60g black olives', '½ red onion', '2 tbsp olive oil', '1 lemon', 'Fresh parsley', '1 tsp dried oregano'],
    preparation: 'Drain chickpeas. Combine all vegetables. Dress with olive oil, lemon juice and oregano. Toss well, let sit 10 min for flavours to meld.',
    excludeFor: ['low_carb'],
  },
  {
    id: 'l10',
    name: 'Asian Beef & Cabbage Salad',
    type: 'lunch',
    description: 'Thinly sliced grilled beef over shredded cabbage with sesame dressing and crispy shallots.',
    calories: 410,
    protein: 36,
    carbs: 16,
    fat: 22,
    fiber: 4,
    ingredients: ['150g beef steak', '2 cups shredded cabbage', '1 carrot, julienned', '2 spring onions', '2 tbsp soy sauce', '1 tbsp sesame oil', '1 tbsp rice vinegar', '1 tsp honey', 'Sesame seeds', 'Crispy shallots'],
    preparation: 'Grill steak to desired doneness, rest 5 min, slice thin. Whisk dressing ingredients. Toss cabbage and carrot with dressing, top with beef, sesame seeds and shallots.',
    excludeFor: ['vegetarian', 'vegan'],
  },
  {
    id: 'l11',
    name: 'Egg Salad Stuffed Bell Peppers',
    type: 'lunch',
    description: 'Creamy egg salad with Dijon mustard and celery served inside sweet bell pepper halves.',
    calories: 290,
    protein: 18,
    carbs: 12,
    fat: 18,
    fiber: 3,
    ingredients: ['4 hard-boiled eggs', '2 tbsp mayonnaise', '1 tsp Dijon mustard', '2 celery stalks, diced', '2 bell peppers, halved', 'Chives', 'Paprika', 'Salt & pepper'],
    preparation: 'Chop eggs, mix with mayo, mustard, celery, salt and pepper. Halve and de-seed peppers. Fill with egg salad and garnish with chives and paprika.',
    excludeFor: ['vegan', 'dairy_free'],
  },
  {
    id: 'l12',
    name: 'Cauliflower Tabbouleh',
    type: 'lunch',
    description: 'Cauliflower rice tabbouleh with fresh herbs, tomatoes and a lemon-olive oil dressing — grain-free twist on a classic.',
    calories: 220,
    protein: 6,
    carbs: 18,
    fat: 12,
    fiber: 6,
    ingredients: ['1 small cauliflower, riced', '1 cup fresh parsley, chopped', '½ cup fresh mint', '2 tomatoes, diced', '½ cucumber, diced', '3 tbsp olive oil', '2 lemons', 'Salt & pepper'],
    preparation: 'Pulse cauliflower into rice-sized pieces. Combine with herbs, tomatoes and cucumber. Dress with olive oil and lemon juice. Season well and refrigerate 30 min.',
    excludeFor: [],
  },

  // ─── DINNER ───────────────────────────────────────────────────────────────
  {
    id: 'd1',
    name: 'Baked Salmon with Asparagus',
    type: 'dinner',
    description: 'Herb-crusted salmon fillet baked alongside tender asparagus spears — omega-3 rich and elegant.',
    calories: 440,
    protein: 44,
    carbs: 10,
    fat: 24,
    fiber: 4,
    ingredients: ['200g salmon fillet', '200g asparagus', '2 tbsp olive oil', '2 garlic cloves', '1 lemon', 'Fresh dill', 'Salt & pepper'],
    preparation: 'Preheat oven 200 °C. Rub salmon with oil, garlic and dill. Arrange asparagus on baking sheet, place salmon on top. Bake 15–18 min. Squeeze lemon before serving.',
    excludeFor: ['vegetarian', 'vegan'],
  },
  {
    id: 'd2',
    name: 'Grilled Chicken with Roasted Vegetables',
    type: 'dinner',
    description: 'Marinated chicken thighs alongside roasted courgette, peppers and red onion.',
    calories: 430,
    protein: 42,
    carbs: 18,
    fat: 18,
    fiber: 5,
    ingredients: ['200g chicken thighs', '1 courgette', '1 bell pepper', '1 red onion', '2 tbsp olive oil', '2 garlic cloves', 'Rosemary', 'Thyme', 'Salt & pepper', 'Lemon'],
    preparation: 'Marinate chicken in olive oil, garlic and herbs 30 min. Roast vegetables at 200 °C for 20 min. Grill chicken 6–7 min per side. Rest and serve together.',
    excludeFor: ['vegetarian', 'vegan'],
  },
  {
    id: 'd3',
    name: 'Beef & Broccoli Stir-Fry',
    type: 'dinner',
    description: 'Tender beef strips with crispy broccoli in a rich soy-ginger sauce — a weeknight classic.',
    calories: 450,
    protein: 40,
    carbs: 18,
    fat: 22,
    fiber: 4,
    ingredients: ['200g beef sirloin, sliced thin', '2 cups broccoli florets', '3 tbsp soy sauce', '1 tbsp oyster sauce', '1 tbsp sesame oil', '1 tsp cornstarch', '3 garlic cloves', '1 tsp ginger', '1 tbsp coconut oil'],
    preparation: 'Marinate beef with soy sauce and cornstarch 10 min. Stir-fry beef in hot oil 3 min, remove. Cook broccoli and garlic 3 min. Return beef, add remaining sauces, toss.',
    excludeFor: ['vegetarian', 'vegan'],
  },
  {
    id: 'd4',
    name: 'Coconut Prawn Curry',
    type: 'dinner',
    description: 'Juicy prawns in a fragrant coconut milk curry with spinach and tomatoes — rich and comforting.',
    calories: 390,
    protein: 34,
    carbs: 16,
    fat: 22,
    fiber: 3,
    ingredients: ['200g raw prawns', '400ml coconut milk', '1 onion', '2 tomatoes', '2 cups spinach', '2 garlic cloves', '1 tbsp ginger', '2 tsp curry powder', '1 tsp turmeric', '1 tbsp coconut oil', 'Fresh cilantro'],
    preparation: 'Sauté onion, garlic and ginger in oil 5 min. Add spices, cook 1 min. Pour in coconut milk and tomatoes, simmer 10 min. Add prawns and spinach, cook 4 min until pink.',
    excludeFor: ['vegetarian', 'vegan'],
  },
  {
    id: 'd5',
    name: 'Turkey Meatballs with Zucchini Noodles',
    type: 'dinner',
    description: 'Herby turkey meatballs over spiralised zucchini in a light tomato sauce — comforting but low-carb.',
    calories: 400,
    protein: 38,
    carbs: 16,
    fat: 18,
    fiber: 4,
    ingredients: ['250g ground turkey', '2 large zucchini', '400g crushed tomatoes', '1 egg', '2 garlic cloves', '1 tbsp olive oil', 'Italian seasoning', 'Parmesan', 'Fresh basil', 'Salt & pepper'],
    preparation: 'Mix turkey with egg, garlic and seasoning. Roll into balls, brown in oil 8 min. Simmer in tomatoes 10 min. Spiralise zucchini, toss with a little oil, top with sauce and meatballs.',
    excludeFor: ['vegetarian', 'vegan'],
  },
  {
    id: 'd6',
    name: 'Stuffed Bell Peppers with Ground Beef',
    type: 'dinner',
    description: 'Bell peppers filled with seasoned ground beef, diced tomatoes and herbs — vibrant and wholesome.',
    calories: 420,
    protein: 36,
    carbs: 20,
    fat: 20,
    fiber: 5,
    ingredients: ['4 bell peppers', '300g ground beef', '400g diced tomatoes', '1 onion', '2 garlic cloves', '1 tsp cumin', '1 tsp smoked paprika', '2 tbsp olive oil', 'Fresh parsley'],
    preparation: 'Cut off pepper tops, de-seed. Brown beef with onion and garlic. Add spices and tomatoes, simmer 8 min. Fill peppers, bake 200 °C for 25 min until tender.',
    excludeFor: ['vegetarian', 'vegan'],
  },
  {
    id: 'd7',
    name: 'Baked Cod with Mediterranean Vegetables',
    type: 'dinner',
    description: 'Flaky cod baked on a bed of olives, capers, tomatoes and herbs — simple and full of flavour.',
    calories: 340,
    protein: 38,
    carbs: 12,
    fat: 14,
    fiber: 3,
    ingredients: ['200g cod fillet', '200g cherry tomatoes', '60g kalamata olives', '2 tbsp capers', '3 tbsp olive oil', '3 garlic cloves', 'Fresh thyme', 'Lemon', 'Salt & pepper'],
    preparation: 'Layer tomatoes, olives and capers in baking dish with oil and garlic. Place cod on top, season, add thyme and lemon slices. Bake 180 °C for 20 min.',
    excludeFor: ['vegetarian', 'vegan'],
  },
  {
    id: 'd8',
    name: 'Pork Tenderloin with Apple & Fennel',
    type: 'dinner',
    description: 'Roasted pork tenderloin with caramelised apple slices and fennel — sweet, savory and impressive.',
    calories: 390,
    protein: 40,
    carbs: 22,
    fat: 14,
    fiber: 4,
    ingredients: ['250g pork tenderloin', '1 apple, sliced', '1 fennel bulb, sliced', '1 onion', '1 tbsp olive oil', '1 tsp Dijon mustard', 'Fresh thyme', 'Salt & pepper'],
    preparation: 'Sear tenderloin in oil 3 min per side. Rub with mustard and thyme. Arrange apple, fennel and onion around it. Roast 200 °C for 20 min. Rest 5 min before slicing.',
    excludeFor: ['vegetarian', 'vegan'],
  },
  {
    id: 'd9',
    name: 'Black Bean & Sweet Potato Bowl',
    type: 'dinner',
    description: 'Roasted sweet potato with spiced black beans, avocado and a lime-cumin dressing — plant-based and hearty.',
    calories: 430,
    protein: 14,
    carbs: 60,
    fat: 14,
    fiber: 16,
    ingredients: ['1 sweet potato, cubed', '400g canned black beans', '1 avocado', '1 lime', '2 tbsp olive oil', '1 tsp cumin', '1 tsp smoked paprika', 'Fresh cilantro', 'Salt & pepper'],
    preparation: 'Roast sweet potato with oil, cumin and paprika at 220 °C for 25 min. Season beans with lime, cumin and salt. Serve potato over beans, top with avocado and cilantro.',
    excludeFor: ['low_carb'],
  },
  {
    id: 'd10',
    name: 'Lamb Chops with Roasted Root Vegetables',
    type: 'dinner',
    description: 'Rosemary-marinated lamb chops with honey-roasted parsnips and carrots.',
    calories: 520,
    protein: 44,
    carbs: 24,
    fat: 26,
    fiber: 5,
    ingredients: ['2 lamb chops', '2 parsnips', '2 carrots', '1 tbsp olive oil', '1 tsp honey', 'Fresh rosemary', '3 garlic cloves', 'Salt & pepper'],
    preparation: 'Marinate lamb with rosemary and garlic 1 hour. Toss root vegetables with oil and honey. Roast veg 35 min at 200 °C. Grill lamb 4 min per side. Rest before serving.',
    excludeFor: ['vegetarian', 'vegan'],
  },
  {
    id: 'd11',
    name: 'Chicken Tikka Masala',
    type: 'dinner',
    description: 'Tender chicken in a rich, spiced tomato-cream sauce — a crowd-pleasing classic made from scratch.',
    calories: 460,
    protein: 42,
    carbs: 18,
    fat: 24,
    fiber: 3,
    ingredients: ['200g chicken breast', '400g crushed tomatoes', '100ml cream', '1 onion', '3 garlic cloves', '1 tbsp ginger', '2 tsp garam masala', '1 tsp cumin', '1 tsp turmeric', '1 tbsp olive oil', 'Fresh cilantro'],
    preparation: 'Marinate chicken in spices and yogurt 1 hour. Grill or pan-fry 8 min. Make sauce: sauté onion, garlic, ginger, add spices and tomatoes, simmer 15 min, blend, add cream. Add chicken and simmer 5 min.',
    excludeFor: ['vegetarian', 'vegan', 'dairy_free'],
  },
  {
    id: 'd12',
    name: 'Lemon Herb Baked Chicken with Cauliflower Rice',
    type: 'dinner',
    description: 'Juicy baked chicken thighs over herbed cauliflower rice — clean, fresh and satisfying.',
    calories: 380,
    protein: 44,
    carbs: 12,
    fat: 16,
    fiber: 4,
    ingredients: ['200g chicken thighs', '1 small cauliflower', '2 lemons', '3 tbsp olive oil', '4 garlic cloves', 'Fresh parsley', 'Thyme', 'Salt & pepper'],
    preparation: 'Marinate chicken in lemon, garlic, herbs and oil 30 min. Bake 200 °C for 30 min. Rice cauliflower in food processor, sauté in oil 5 min. Season. Serve chicken over cauliflower rice.',
    excludeFor: ['vegetarian', 'vegan'],
  },

  // ─── SNACKS ───────────────────────────────────────────────────────────────
  {
    id: 's1',
    name: 'Apple Slices with Almond Butter',
    type: 'snack',
    description: 'Crisp apple slices paired with creamy almond butter — the perfect balance of sweet and satisfying.',
    calories: 200,
    protein: 5,
    carbs: 24,
    fat: 10,
    fiber: 4,
    ingredients: ['1 apple', '2 tbsp almond butter', 'Cinnamon (optional)'],
    preparation: 'Core and slice apple. Serve with almond butter for dipping. Dust with cinnamon if desired.',
    excludeFor: ['nut_free'],
  },
  {
    id: 's2',
    name: 'Celery Sticks with Hummus',
    type: 'snack',
    description: 'Crunchy celery sticks with creamy homemade-style hummus — light, fresh and fibre-rich.',
    calories: 140,
    protein: 5,
    carbs: 16,
    fat: 6,
    fiber: 5,
    ingredients: ['4 celery stalks', '4 tbsp hummus', 'Paprika', 'Olive oil'],
    preparation: 'Cut celery into sticks. Serve alongside hummus drizzled with olive oil and paprika.',
    excludeFor: [],
  },
  {
    id: 's3',
    name: 'Mixed Nuts & Dried Cranberries',
    type: 'snack',
    description: 'A handful of mixed nuts and tart cranberries — nutrient-dense and easy to take anywhere.',
    calories: 220,
    protein: 6,
    carbs: 18,
    fat: 14,
    fiber: 2,
    ingredients: ['20g almonds', '10g walnuts', '10g cashews', '15g dried cranberries'],
    preparation: 'Measure out and combine. Best consumed fresh; can be portioned into snack bags in advance.',
    excludeFor: ['nut_free'],
  },
  {
    id: 's4',
    name: 'Greek Yogurt with Honey & Walnuts',
    type: 'snack',
    description: 'Thick Greek yogurt with a swirl of honey and crunchy walnuts — indulgent yet nutritious.',
    calories: 230,
    protein: 14,
    carbs: 18,
    fat: 10,
    fiber: 1,
    ingredients: ['150g Greek yogurt', '1 tbsp honey', '15g walnuts, chopped'],
    preparation: 'Spoon yogurt into a bowl. Drizzle honey over the top and scatter walnuts.',
    excludeFor: ['vegan', 'dairy_free', 'nut_free'],
  },
  {
    id: 's5',
    name: 'Hard-Boiled Eggs with Everything Seasoning',
    type: 'snack',
    description: 'Protein-packed hard-boiled eggs dusted with everything bagel seasoning — simple and filling.',
    calories: 150,
    protein: 12,
    carbs: 2,
    fat: 10,
    fiber: 0,
    ingredients: ['2 eggs', '1 tsp everything bagel seasoning', 'Salt'],
    preparation: 'Boil eggs 10 min, cool in ice water, peel. Halve and sprinkle with everything seasoning.',
    excludeFor: ['vegan'],
  },
  {
    id: 's6',
    name: 'Edamame with Sea Salt',
    type: 'snack',
    description: 'Steamed edamame pods with flaky sea salt — rich in plant protein and fun to eat.',
    calories: 160,
    protein: 12,
    carbs: 12,
    fat: 5,
    fiber: 5,
    ingredients: ['1 cup edamame (in pods)', 'Flaky sea salt'],
    preparation: 'Boil or microwave edamame 3–5 min until tender. Drain and toss with sea salt.',
    excludeFor: [],
  },
  {
    id: 's7',
    name: 'Cucumber Rounds with Tzatziki',
    type: 'snack',
    description: 'Cool cucumber slices with homemade tzatziki — refreshing and low-calorie.',
    calories: 120,
    protein: 5,
    carbs: 8,
    fat: 7,
    fiber: 1,
    ingredients: ['1 cucumber', '80g Greek yogurt', '½ garlic clove', '1 tbsp olive oil', 'Fresh mint', 'Salt'],
    preparation: 'Slice cucumber into rounds. Mix yogurt with grated garlic, oil, salt and mint. Serve as a dip.',
    excludeFor: ['vegan', 'dairy_free'],
  },
  {
    id: 's8',
    name: 'Sliced Turkey & Avocado Roll-Ups',
    type: 'snack',
    description: 'Thin turkey slices rolled around avocado and rocket — a no-carb, high-protein bite.',
    calories: 180,
    protein: 16,
    carbs: 5,
    fat: 11,
    fiber: 3,
    ingredients: ['80g sliced turkey breast', '½ avocado, sliced', 'Handful of rocket', 'Lemon juice', 'Salt & pepper'],
    preparation: 'Lay turkey slices flat. Place avocado and rocket at one end. Season with lemon and salt. Roll up tightly and secure with a toothpick.',
    excludeFor: ['vegetarian', 'vegan'],
  },
  {
    id: 's9',
    name: 'Berries & Cottage Cheese',
    type: 'snack',
    description: 'Fresh berries stirred into creamy cottage cheese — protein-rich, refreshing and satisfying.',
    calories: 160,
    protein: 14,
    carbs: 14,
    fat: 3,
    fiber: 2,
    ingredients: ['150g cottage cheese', '½ cup mixed berries', '1 tsp vanilla extract'],
    preparation: 'Combine cottage cheese with vanilla. Top with fresh berries.',
    excludeFor: ['vegan', 'dairy_free'],
  },
  {
    id: 's10',
    name: 'Dark Chocolate & Almonds',
    type: 'snack',
    description: 'A square of dark chocolate with a small handful of almonds — antioxidant-rich and satisfying.',
    calories: 210,
    protein: 5,
    carbs: 16,
    fat: 14,
    fiber: 3,
    ingredients: ['20g dark chocolate (70%+)', '20g raw almonds'],
    preparation: 'Break chocolate into squares. Pair with almonds for a balanced sweet-savoury snack.',
    excludeFor: ['nut_free'],
  },
];

export const motivationalMessages: string[] = [
  'Every nutritious meal is a step towards the healthiest version of you. Keep it up!',
  'You are what you eat — so today, choose to be vibrant, strong and energised!',
  'Small consistent choices add up to big results. Today\'s meal plan is your foundation.',
  'Nourishing your body is an act of self-love. You deserve to feel great!',
  'Progress is progress, no matter how small. Celebrating your healthy choices matters.',
  'Your body is your most valuable asset — fuel it with care and intention today.',
  'Healthy eating isn\'t a diet, it\'s a lifestyle. You\'re building something that lasts.',
  'Each meal you plan is a commitment to your wellbeing. That\'s something to be proud of.',
  'The best time to eat well was yesterday — the second best time is right now!',
  'Consistency beats perfection every time. Keep showing up for yourself.',
  'You have the power to transform your health one meal at a time. Let\'s do this!',
  'Real food, real results. Your body will thank you for every healthy bite.',
  'Think of healthy eating as a gift to your future self. Unwrap it every day.',
  'You don\'t have to eat less — you just have to eat right. Today\'s plan has you covered.',
  'Energy, clarity, confidence — all on your plate. Enjoy today\'s meals!',
  'Meal by meal, day by day, you\'re creating a healthier you. That\'s remarkable.',
  'Greatness is built in the small moments. Like choosing a nutritious breakfast.',
  'Your commitment to healthy eating inspires those around you. Keep leading by example.',
  'Fuelling your body well isn\'t just about weight — it\'s about living fully.',
  'Today is a new opportunity to nourish yourself. Make the most of it!',
];
