import type { Meal } from './types';

export const meals: Meal[] = [
  // ─── BREAKFAST ────────────────────────────────────────────────────────────
  {
    id: 'b1',
    name: 'Scrambled Eggs with Spinach & Tomatoes',
    type: 'breakfast',
    description: 'Fluffy scrambled eggs loaded with fresh spinach and cherry tomatoes — a protein-rich start to your day.',
    calories: 320,
    protein: 22,
    carbs: 8,
    fat: 22,
    fiber: 2,
    ingredients: ['3 large eggs', '1 cup baby spinach', '½ cup cherry tomatoes', '1 tbsp olive oil', 'Salt & pepper', 'Fresh chives'],
    preparation: 'Whisk eggs with a pinch of salt. Heat olive oil in a non-stick pan, sauté tomatoes 1 min, add spinach until wilted, then pour in eggs and fold gently until just set. Top with chives.',
    excludeFor: [],
  },
  {
    id: 'b2',
    name: 'Greek Yogurt Parfait with Berries',
    type: 'breakfast',
    description: 'Creamy Greek yogurt layered with mixed berries and a drizzle of honey for natural sweetness.',
    calories: 280,
    protein: 18,
    carbs: 32,
    fat: 6,
    fiber: 4,
    ingredients: ['200g Greek yogurt (full-fat)', '½ cup mixed berries', '1 tbsp honey', '1 tbsp chia seeds', 'Fresh mint'],
    preparation: 'Layer yogurt in a bowl or glass, top with berries, sprinkle chia seeds, drizzle honey and garnish with mint.',
    excludeFor: ['vegan', 'dairy_free'],
  },
  {
    id: 'b3',
    name: 'Avocado & Poached Egg Bowl',
    type: 'breakfast',
    description: 'Halved avocado topped with a perfectly poached egg — creamy, satisfying and full of healthy fats.',
    calories: 350,
    protein: 14,
    carbs: 10,
    fat: 28,
    fiber: 7,
    ingredients: ['1 ripe avocado', '2 eggs', '½ lemon', 'Red pepper flakes', 'Salt & pepper', '1 tsp white vinegar'],
    preparation: 'Bring water to a gentle simmer, add vinegar. Crack each egg into a cup and slide in. Poach 3 min. Halve avocado, season with lemon, salt and pepper flakes, top with eggs.',
    excludeFor: ['vegan'],
  },
  {
    id: 'b4',
    name: 'Chia Seed Pudding with Mango',
    type: 'breakfast',
    description: 'Make-ahead chia pudding with luscious mango and toasted coconut — vibrant and refreshing.',
    calories: 290,
    protein: 8,
    carbs: 36,
    fat: 12,
    fiber: 11,
    ingredients: ['3 tbsp chia seeds', '1 cup coconut milk', '1 ripe mango, diced', '1 tbsp shredded coconut', '1 tsp vanilla extract', '1 tsp maple syrup'],
    preparation: 'Mix chia seeds with coconut milk, vanilla and maple syrup. Refrigerate overnight (min 4 h). Top with fresh mango and toasted coconut.',
    excludeFor: ['nut_free'],
  },
  {
    id: 'b5',
    name: 'Spinach & Feta Frittata',
    type: 'breakfast',
    description: 'Oven-baked egg frittata packed with spinach, feta and herbs — ideal for meal prep.',
    calories: 360,
    protein: 26,
    carbs: 6,
    fat: 26,
    fiber: 1,
    ingredients: ['4 eggs', '100g feta cheese', '2 cups spinach', '¼ red onion, sliced', '1 tbsp olive oil', 'Dried oregano', 'Salt & pepper'],
    preparation: 'Preheat oven to 180 °C. Sauté onion in oven-safe skillet, add spinach until wilted. Pour whisked eggs over, crumble feta on top, season and bake 15 min until set.',
    excludeFor: ['vegan', 'dairy_free'],
  },
  {
    id: 'b6',
    name: 'Smoked Salmon & Cucumber Rolls',
    type: 'breakfast',
    description: 'Thin cucumber ribbons wrapped around cream cheese and smoked salmon — elegant and light.',
    calories: 240,
    protein: 20,
    carbs: 5,
    fat: 15,
    fiber: 1,
    ingredients: ['100g smoked salmon', '60g cream cheese', '1 large cucumber', '1 tbsp capers', 'Fresh dill', 'Lemon zest'],
    preparation: 'Use a peeler to make long cucumber ribbons. Spread cream cheese on each ribbon, place salmon, capers and dill, then roll up and secure with a toothpick.',
    excludeFor: ['vegetarian', 'vegan', 'dairy_free'],
  },
  {
    id: 'b7',
    name: 'Cottage Cheese Bowl with Peaches & Almonds',
    type: 'breakfast',
    description: 'Creamy cottage cheese with sliced peaches and crunchy almonds — high protein and satisfying.',
    calories: 310,
    protein: 28,
    carbs: 22,
    fat: 10,
    fiber: 2,
    ingredients: ['200g cottage cheese', '1 ripe peach, sliced', '20g sliced almonds', '1 tsp honey', 'Cinnamon'],
    preparation: 'Spoon cottage cheese into a bowl. Arrange peach slices, scatter almonds, drizzle honey and dust with cinnamon.',
    excludeFor: ['vegan', 'dairy_free', 'nut_free'],
  },
  {
    id: 'b8',
    name: 'Vegetable Omelette with Goat Cheese',
    type: 'breakfast',
    description: 'Three-egg omelette stuffed with colourful peppers, mushrooms and tangy goat cheese.',
    calories: 380,
    protein: 28,
    carbs: 9,
    fat: 26,
    fiber: 2,
    ingredients: ['3 eggs', '50g goat cheese', '½ bell pepper, diced', '4 mushrooms, sliced', '¼ cup onion, diced', '1 tbsp butter', 'Chives', 'Salt & pepper'],
    preparation: 'Sauté vegetables in butter 3 min. Whisk eggs, pour into pan over vegetables. When edges set, crumble goat cheese on half, fold over and slide onto plate.',
    excludeFor: ['vegan', 'dairy_free'],
  },
  {
    id: 'b9',
    name: 'Green Protein Smoothie Bowl',
    type: 'breakfast',
    description: 'Thick blended smoothie of banana, spinach and almond butter, topped with seeds and coconut.',
    calories: 340,
    protein: 14,
    carbs: 38,
    fat: 16,
    fiber: 7,
    ingredients: ['1 frozen banana', '2 cups spinach', '2 tbsp almond butter', '1 cup almond milk', '1 tbsp hemp seeds', '1 tbsp pumpkin seeds', '2 tbsp shredded coconut'],
    preparation: 'Blend banana, spinach, almond butter and almond milk until thick and smooth. Pour into a bowl and top with seeds and coconut.',
    excludeFor: ['nut_free'],
  },
  {
    id: 'b10',
    name: 'Turkey & Vegetable Egg Cups',
    type: 'breakfast',
    description: 'Oven-baked egg cups lined with turkey slices, filled with vegetables — portable and protein-packed.',
    calories: 290,
    protein: 30,
    carbs: 5,
    fat: 16,
    fiber: 1,
    ingredients: ['4 thin-sliced turkey breast', '4 eggs', '½ cup diced bell peppers', '½ cup baby spinach', '2 tbsp salsa', 'Salt & pepper'],
    preparation: 'Preheat oven 180 °C. Line muffin tins with turkey slices, add a spoonful of veggies and salsa, crack an egg over each. Season and bake 15–18 min until set.',
    excludeFor: ['vegetarian', 'vegan'],
  },
  {
    id: 'b11',
    name: 'Quinoa Breakfast Bowl with Berries',
    type: 'breakfast',
    description: 'Warm quinoa porridge with almond milk, cinnamon and fresh berries — a hearty grain-free alternative.',
    calories: 360,
    protein: 12,
    carbs: 52,
    fat: 9,
    fiber: 6,
    ingredients: ['½ cup quinoa', '1 cup almond milk', '½ cup mixed berries', '1 tbsp maple syrup', '½ tsp cinnamon', '1 tbsp pumpkin seeds'],
    preparation: 'Cook quinoa in almond milk with cinnamon over medium heat ~15 min until creamy. Top with berries, seeds and maple syrup.',
    excludeFor: ['no_bread', 'low_carb'],
  },
  {
    id: 'b12',
    name: 'Baked Egg & Tomato Shakshuka',
    type: 'breakfast',
    description: 'Eggs poached in a spiced tomato and pepper sauce — a North African classic bursting with flavour.',
    calories: 300,
    protein: 16,
    carbs: 20,
    fat: 16,
    fiber: 5,
    ingredients: ['3 eggs', '400g crushed tomatoes', '1 red pepper', '1 onion', '2 garlic cloves', '1 tsp cumin', '1 tsp paprika', '½ tsp cayenne', '2 tbsp olive oil', 'Fresh parsley'],
    preparation: 'Sauté onion and pepper 5 min, add garlic and spices. Pour in tomatoes, simmer 10 min. Make wells, crack eggs in, cover and cook 6–8 min until whites are set.',
    excludeFor: ['vegan'],
  },

  // ─── LUNCH ────────────────────────────────────────────────────────────────
  {
    id: 'l1',
    name: 'Grilled Chicken Caesar Salad',
    type: 'lunch',
    description: 'Juicy grilled chicken strips over crispy romaine with a light Caesar dressing and parmesan.',
    calories: 420,
    protein: 40,
    carbs: 8,
    fat: 24,
    fiber: 3,
    ingredients: ['150g chicken breast', '2 cups romaine lettuce', '30g parmesan', '2 tbsp Caesar dressing', 'Lemon juice', 'Black pepper', '1 tbsp olive oil'],
    preparation: 'Season chicken with salt, pepper and lemon juice. Grill 6 min per side. Slice and toss with romaine, parmesan and dressing.',
    excludeFor: ['vegetarian', 'vegan'],
  },
  {
    id: 'l2',
    name: 'Tuna & Avocado Salad',
    type: 'lunch',
    description: 'Chunky tuna mixed with ripe avocado, cucumber and lime — satisfying without any grains.',
    calories: 370,
    protein: 32,
    carbs: 12,
    fat: 22,
    fiber: 6,
    ingredients: ['150g canned tuna (in water)', '1 avocado', '½ cucumber, diced', '½ red onion, diced', '1 lime', '1 tbsp olive oil', 'Fresh cilantro', 'Salt & pepper'],
    preparation: 'Drain tuna. Mash avocado with lime juice. Fold in tuna, cucumber and onion. Season and garnish with cilantro.',
    excludeFor: ['vegetarian', 'vegan'],
  },
  {
    id: 'l3',
    name: 'Red Lentil Soup',
    type: 'lunch',
    description: 'Hearty red lentil soup with cumin and turmeric — warming, filling and naturally plant-based.',
    calories: 320,
    protein: 18,
    carbs: 48,
    fat: 6,
    fiber: 14,
    ingredients: ['1 cup red lentils', '1 onion', '2 carrots', '2 garlic cloves', '1 tsp cumin', '1 tsp turmeric', '1 litre vegetable stock', '2 tbsp olive oil', 'Lemon juice', 'Fresh parsley'],
    preparation: 'Sauté onion, carrot and garlic 5 min. Add lentils, spices and stock, simmer 20 min. Blend half the soup for a creamy texture. Finish with lemon juice and parsley.',
    excludeFor: ['low_carb'],
  },
  {
    id: 'l4',
    name: 'Turkey Lettuce Wraps',
    type: 'lunch',
    description: 'Seasoned ground turkey in crisp butter lettuce cups with hoisin and sesame — light and fun.',
    calories: 350,
    protein: 34,
    carbs: 14,
    fat: 16,
    fiber: 3,
    ingredients: ['200g ground turkey', '8 butter lettuce leaves', '1 tbsp hoisin sauce', '1 tbsp soy sauce (or tamari)', '1 tsp sesame oil', '1 carrot, shredded', '2 spring onions', '1 tsp ginger, grated', '1 garlic clove'],
    preparation: 'Brown turkey with garlic and ginger. Add sauces and sesame oil, cook 2 min. Serve in lettuce cups, top with carrot and spring onion.',
    excludeFor: ['vegetarian', 'vegan'],
  },
  {
    id: 'l5',
    name: 'Greek Salad with Grilled Halloumi',
    type: 'lunch',
    description: 'Classic Greek salad with juicy tomatoes, kalamata olives and salty grilled halloumi slices.',
    calories: 400,
    protein: 20,
    carbs: 14,
    fat: 28,
    fiber: 4,
    ingredients: ['150g halloumi', '2 tomatoes', '½ cucumber', '½ red onion', '80g kalamata olives', '2 tbsp olive oil', '1 tbsp red wine vinegar', 'Dried oregano'],
    preparation: 'Grill halloumi slices 2 min per side until golden. Chop vegetables, combine with olives. Dress with oil, vinegar and oregano. Top with halloumi.',
    excludeFor: ['vegan', 'dairy_free'],
  },
  {
    id: 'l6',
    name: 'Zucchini Noodles with Pesto & Cherry Tomatoes',
    type: 'lunch',
    description: 'Spiralised zucchini tossed in basil pesto with burst cherry tomatoes and pine nuts.',
    calories: 300,
    protein: 8,
    carbs: 16,
    fat: 22,
    fiber: 4,
    ingredients: ['2 medium zucchini', '3 tbsp basil pesto', '1 cup cherry tomatoes', '2 tbsp pine nuts', 'Parmesan (optional)', 'Salt & pepper'],
    preparation: 'Spiralise zucchini. Halve and pan-roast tomatoes 3 min until blistered. Toss noodles with pesto (no heat needed). Top with tomatoes and pine nuts.',
    excludeFor: ['nut_free', 'low_carb'],
  },
  {
    id: 'l7',
    name: 'Smoked Salmon & Cucumber Bites',
    type: 'lunch',
    description: 'Thick cucumber rounds topped with herbed cream cheese and smoked salmon — zero grains required.',
    calories: 250,
    protein: 22,
    carbs: 6,
    fat: 15,
    fiber: 1,
    ingredients: ['100g smoked salmon', '80g cream cheese', '1 large cucumber', '1 tbsp capers', 'Fresh dill', 'Lemon zest', 'Black pepper'],
    preparation: 'Slice cucumber into thick rounds. Mix cream cheese with dill and lemon zest. Pipe or spread onto cucumber, top with salmon and capers.',
    excludeFor: ['vegetarian', 'vegan', 'dairy_free'],
  },
  {
    id: 'l8',
    name: 'Chicken & Vegetable Stir-Fry',
    type: 'lunch',
    description: 'Tender chicken with crisp broccoli, peppers and snap peas in a ginger-soy sauce.',
    calories: 380,
    protein: 38,
    carbs: 20,
    fat: 14,
    fiber: 5,
    ingredients: ['150g chicken breast, sliced', '1 cup broccoli florets', '1 bell pepper', '1 cup snap peas', '2 tbsp soy sauce (or tamari)', '1 tsp sesame oil', '1 tbsp oyster sauce', '1 tsp ginger', '1 garlic clove', '1 tbsp olive oil'],
    preparation: 'Stir-fry chicken in hot oil 4 min. Remove. Stir-fry vegetables 3 min. Return chicken, add sauces, ginger and garlic. Toss to coat and serve.',
    excludeFor: ['vegetarian', 'vegan'],
  },
  {
    id: 'l9',
    name: 'Mediterranean Chickpea Salad',
    type: 'lunch',
    description: 'Chickpeas with roasted peppers, cucumber, olives and fresh herbs in a lemon-oregano dressing.',
    calories: 340,
    protein: 14,
    carbs: 42,
    fat: 12,
    fiber: 12,
    ingredients: ['400g canned chickpeas', '1 roasted red pepper', '½ cucumber, diced', '60g black olives', '½ red onion', '2 tbsp olive oil', '1 lemon', 'Fresh parsley', '1 tsp dried oregano'],
    preparation: 'Drain chickpeas. Combine all vegetables. Dress with olive oil, lemon juice and oregano. Toss well, let sit 10 min for flavours to meld.',
    excludeFor: ['low_carb'],
  },
  {
    id: 'l10',
    name: 'Asian Beef & Cabbage Salad',
    type: 'lunch',
    description: 'Thinly sliced grilled beef over shredded cabbage with sesame dressing and crispy shallots.',
    calories: 410,
    protein: 36,
    carbs: 16,
    fat: 22,
    fiber: 4,
    ingredients: ['150g beef steak', '2 cups shredded cabbage', '1 carrot, julienned', '2 spring onions', '2 tbsp soy sauce', '1 tbsp sesame oil', '1 tbsp rice vinegar', '1 tsp honey', 'Sesame seeds', 'Crispy shallots'],
    preparation: 'Grill steak to desired doneness, rest 5 min, slice thin. Whisk dressing ingredients. Toss cabbage and carrot with dressing, top with beef, sesame seeds and shallots.',
    excludeFor: ['vegetarian', 'vegan'],
  },
  {
    id: 'l11',
    name: 'Egg Salad Stuffed Bell Peppers',
    type: 'lunch',
    description: 'Creamy egg salad with Dijon mustard and celery served inside sweet bell pepper halves.',
    calories: 290,
    protein: 18,
    carbs: 12,
    fat: 18,
    fiber: 3,
    ingredients: ['4 hard-boiled eggs', '2 tbsp mayonnaise', '1 tsp Dijon mustard', '2 celery stalks, diced', '2 bell peppers, halved', 'Chives', 'Paprika', 'Salt & pepper'],
    preparation: 'Chop eggs, mix with mayo, mustard, celery, salt and pepper. Halve and de-seed peppers. Fill with egg salad and garnish with chives and paprika.',
    excludeFor: ['vegan', 'dairy_free'],
  },
  {
    id: 'l12',
    name: 'Cauliflower Tabbouleh',
    type: 'lunch',
    description: 'Cauliflower rice tabbouleh with fresh herbs, tomatoes and a lemon-olive oil dressing — grain-free twist on a classic.',
    calories: 220,
    protein: 6,
    carbs: 18,
    fat: 12,
    fiber: 6,
    ingredients: ['1 small cauliflower, riced', '1 cup fresh parsley, chopped', '½ cup fresh mint', '2 tomatoes, diced', '½ cucumber, diced', '3 tbsp olive oil', '2 lemons', 'Salt & pepper'],
    preparation: 'Pulse cauliflower into rice-sized pieces. Combine with herbs, tomatoes and cucumber. Dress with olive oil and lemon juice. Season well and refrigerate 30 min.',
    excludeFor: [],
  },

  // ─── DINNER ───────────────────────────────────────────────────────────────
  {
    id: 'd1',
    name: 'Baked Salmon with Asparagus',
    type: 'dinner',
    description: 'Herb-crusted salmon fillet baked alongside tender asparagus spears — omega-3 rich and elegant.',
    calories: 440,
    protein: 44,
    carbs: 10,
    fat: 24,
    fiber: 4,
    ingredients: ['200g salmon fillet', '200g asparagus', '2 tbsp olive oil', '2 garlic cloves', '1 lemon', 'Fresh dill', 'Salt & pepper'],
    preparation: 'Preheat oven 200 °C. Rub salmon with oil, garlic and dill. Arrange asparagus on baking sheet, place salmon on top. Bake 15–18 min. Squeeze lemon before serving.',
    excludeFor: ['vegetarian', 'vegan'],
  },
  {
    id: 'd2',
    name: 'Grilled Chicken with Roasted Vegetables',
    type: 'dinner',
    description: 'Marinated chicken thighs alongside roasted courgette, peppers and red onion.',
    calories: 430,
    protein: 42,
    carbs: 18,
    fat: 18,
    fiber: 5,
    ingredients: ['200g chicken thighs', '1 courgette', '1 bell pepper', '1 red onion', '2 tbsp olive oil', '2 garlic cloves', 'Rosemary', 'Thyme', 'Salt & pepper', 'Lemon'],
    preparation: 'Marinate chicken in olive oil, garlic and herbs 30 min. Roast vegetables at 200 °C for 20 min. Grill chicken 6–7 min per side. Rest and serve together.',
    excludeFor: ['vegetarian', 'vegan'],
  },
  {
    id: 'd3',
    name: 'Beef & Broccoli Stir-Fry',
    type: 'dinner',
    description: 'Tender beef strips with crispy broccoli in a rich soy-ginger sauce — a weeknight classic.',
    calories: 450,
    protein: 40,
    carbs: 18,
    fat: 22,
    fiber: 4,
    ingredients: ['200g beef sirloin, sliced thin', '2 cups broccoli florets', '3 tbsp soy sauce', '1 tbsp oyster sauce', '1 tbsp sesame oil', '1 tsp cornstarch', '3 garlic cloves', '1 tsp ginger', '1 tbsp coconut oil'],
    preparation: 'Marinate beef with soy sauce and cornstarch 10 min. Stir-fry beef in hot oil 3 min, remove. Cook broccoli and garlic 3 min. Return beef, add remaining sauces, toss.',
    excludeFor: ['vegetarian', 'vegan'],
  },
  {
    id: 'd4',
    name: 'Coconut Prawn Curry',
    type: 'dinner',
    description: 'Juicy prawns in a fragrant coconut milk curry with spinach and tomatoes — rich and comforting.',
    calories: 390,
    protein: 34,
    carbs: 16,
    fat: 22,
    fiber: 3,
    ingredients: ['200g raw prawns', '400ml coconut milk', '1 onion', '2 tomatoes', '2 cups spinach', '2 garlic cloves', '1 tbsp ginger', '2 tsp curry powder', '1 tsp turmeric', '1 tbsp coconut oil', 'Fresh cilantro'],
    preparation: 'Sauté onion, garlic and ginger in oil 5 min. Add spices, cook 1 min. Pour in coconut milk and tomatoes, simmer 10 min. Add prawns and spinach, cook 4 min until pink.',
    excludeFor: ['vegetarian', 'vegan'],
  },
  {
    id: 'd5',
    name: 'Turkey Meatballs with Zucchini Noodles',
    type: 'dinner',
    description: 'Herby turkey meatballs over spiralised zucchini in a light tomato sauce — comforting but low-carb.',
    calories: 400,
    protein: 38,
    carbs: 16,
    fat: 18,
    fiber: 4,
    ingredients: ['250g ground turkey', '2 large zucchini', '400g crushed tomatoes', '1 egg', '2 garlic cloves', '1 tbsp olive oil', 'Italian seasoning', 'Parmesan', 'Fresh basil', 'Salt & pepper'],
    preparation: 'Mix turkey with egg, garlic and seasoning. Roll into balls, brown in oil 8 min. Simmer in tomatoes 10 min. Spiralise zucchini, toss with a little oil, top with sauce and meatballs.',
    excludeFor: ['vegetarian', 'vegan'],
  },
  {
    id: 'd6',
    name: 'Stuffed Bell Peppers with Ground Beef',
    type: 'dinner',
    description: 'Bell peppers filled with seasoned ground beef, diced tomatoes and herbs — vibrant and wholesome.',
    calories: 420,
    protein: 36,
    carbs: 20,
    fat: 20,
    fiber: 5,
    ingredients: ['4 bell peppers', '300g ground beef', '400g diced tomatoes', '1 onion', '2 garlic cloves', '1 tsp cumin', '1 tsp smoked paprika', '2 tbsp olive oil', 'Fresh parsley'],
    preparation: 'Cut off pepper tops, de-seed. Brown beef with onion and garlic. Add spices and tomatoes, simmer 8 min. Fill peppers, bake 200 °C for 25 min until tender.',
    excludeFor: ['vegetarian', 'vegan'],
  },
  {
    id: 'd7',
    name: 'Baked Cod with Mediterranean Vegetables',
    type: 'dinner',
    description: 'Flaky cod baked on a bed of olives, capers, tomatoes and herbs — simple and full of flavour.',
    calories: 340,
    protein: 38,
    carbs: 12,
    fat: 14,
    fiber: 3,
    ingredients: ['200g cod fillet', '200g cherry tomatoes', '60g kalamata olives', '2 tbsp capers', '3 tbsp olive oil', '3 garlic cloves', 'Fresh thyme', 'Lemon', 'Salt & pepper'],
    preparation: 'Layer tomatoes, olives and capers in baking dish with oil and garlic. Place cod on top, season, add thyme and lemon slices. Bake 180 °C for 20 min.',
    excludeFor: ['vegetarian', 'vegan'],
  },
  {
    id: 'd8',
    name: 'Pork Tenderloin with Apple & Fennel',
    type: 'dinner',
    description: 'Roasted pork tenderloin with caramelised apple slices and fennel — sweet, savory and impressive.',
    calories: 390,
    protein: 40,
    carbs: 22,
    fat: 14,
    fiber: 4,
    ingredients: ['250g pork tenderloin', '1 apple, sliced', '1 fennel bulb, sliced', '1 onion', '1 tbsp olive oil', '1 tsp Dijon mustard', 'Fresh thyme', 'Salt & pepper'],
    preparation: 'Sear tenderloin in oil 3 min per side. Rub with mustard and thyme. Arrange apple, fennel and onion around it. Roast 200 °C for 20 min. Rest 5 min before slicing.',
    excludeFor: ['vegetarian', 'vegan'],
  },
  {
    id: 'd9',
    name: 'Black Bean & Sweet Potato Bowl',
    type: 'dinner',
    description: 'Roasted sweet potato with spiced black beans, avocado and a lime-cumin dressing — plant-based and hearty.',
    calories: 430,
    protein: 14,
    carbs: 60,
    fat: 14,
    fiber: 16,
    ingredients: ['1 sweet potato, cubed', '400g canned black beans', '1 avocado', '1 lime', '2 tbsp olive oil', '1 tsp cumin', '1 tsp smoked paprika', 'Fresh cilantro', 'Salt & pepper'],
    preparation: 'Roast sweet potato with oil, cumin and paprika at 220 °C for 25 min. Season beans with lime, cumin and salt. Serve potato over beans, top with avocado and cilantro.',
    excludeFor: ['low_carb'],
  },
  {
    id: 'd10',
    name: 'Lamb Chops with Roasted Root Vegetables',
    type: 'dinner',
    description: 'Rosemary-marinated lamb chops with honey-roasted parsnips and carrots.',
    calories: 520,
    protein: 44,
    carbs: 24,
    fat: 26,
    fiber: 5,
    ingredients: ['2 lamb chops', '2 parsnips', '2 carrots', '1 tbsp olive oil', '1 tsp honey', 'Fresh rosemary', '3 garlic cloves', 'Salt & pepper'],
    preparation: 'Marinate lamb with rosemary and garlic 1 hour. Toss root vegetables with oil and honey. Roast veg 35 min at 200 °C. Grill lamb 4 min per side. Rest before serving.',
    excludeFor: ['vegetarian', 'vegan'],
  },
  {
    id: 'd11',
    name: 'Chicken Tikka Masala',
    type: 'dinner',
    description: 'Tender chicken in a rich, spiced tomato-cream sauce — a crowd-pleasing classic made from scratch.',
    calories: 460,
    protein: 42,
    carbs: 18,
    fat: 24,
    fiber: 3,
    ingredients: ['200g chicken breast', '400g crushed tomatoes', '100ml cream', '1 onion', '3 garlic cloves', '1 tbsp ginger', '2 tsp garam masala', '1 tsp cumin', '1 tsp turmeric', '1 tbsp olive oil', 'Fresh cilantro'],
    preparation: 'Marinate chicken in spices and yogurt 1 hour. Grill or pan-fry 8 min. Make sauce: sauté onion, garlic, ginger, add spices and tomatoes, simmer 15 min, blend, add cream. Add chicken and simmer 5 min.',
    excludeFor: ['vegetarian', 'vegan', 'dairy_free'],
  },
  {
    id: 'd12',
    name: 'Lemon Herb Baked Chicken with Cauliflower Rice',
    type: 'dinner',
    description: 'Juicy baked chicken thighs over herbed cauliflower rice — clean, fresh and satisfying.',
    calories: 380,
    protein: 44,
    carbs: 12,
    fat: 16,
    fiber: 4,
    ingredients: ['200g chicken thighs', '1 small cauliflower', '2 lemons', '3 tbsp olive oil', '4 garlic cloves', 'Fresh parsley', 'Thyme', 'Salt & pepper'],
    preparation: 'Marinate chicken in lemon, garlic, herbs and oil 30 min. Bake 200 °C for 30 min. Rice cauliflower in food processor, sauté in oil 5 min. Season. Serve chicken over cauliflower rice.',
    excludeFor: ['vegetarian', 'vegan'],
  },

  // ─── SNACKS ───────────────────────────────────────────────────────────────
  {
    id: 's1',
    name: 'Apple Slices with Almond Butter',
    type: 'snack',
    description: 'Crisp apple slices paired with creamy almond butter — the perfect balance of sweet and satisfying.',
    calories: 200,
    protein: 5,
    carbs: 24,
    fat: 10,
    fiber: 4,
    ingredients: ['1 apple', '2 tbsp almond butter', 'Cinnamon (optional)'],
    preparation: 'Core and slice apple. Serve with almond butter for dipping. Dust with cinnamon if desired.',
    excludeFor: ['nut_free'],
  },
  {
    id: 's2',
    name: 'Celery Sticks with Hummus',
    type: 'snack',
    description: 'Crunchy celery sticks with creamy homemade-style hummus — light, fresh and fibre-rich.',
    calories: 140,
    protein: 5,
    carbs: 16,
    fat: 6,
    fiber: 5,
    ingredients: ['4 celery stalks', '4 tbsp hummus', 'Paprika', 'Olive oil'],
    preparation: 'Cut celery into sticks. Serve alongside hummus drizzled with olive oil and paprika.',
    excludeFor: [],
  },
  {
    id: 's3',
    name: 'Mixed Nuts & Dried Cranberries',
    type: 'snack',
    description: 'A handful of mixed nuts and tart cranberries — nutrient-dense and easy to take anywhere.',
    calories: 220,
    protein: 6,
    carbs: 18,
    fat: 14,
    fiber: 2,
    ingredients: ['20g almonds', '10g walnuts', '10g cashews', '15g dried cranberries'],
    preparation: 'Measure out and combine. Best consumed fresh; can be portioned into snack bags in advance.',
    excludeFor: ['nut_free'],
  },
  {
    id: 's4',
    name: 'Greek Yogurt with Honey & Walnuts',
    type: 'snack',
    description: 'Thick Greek yogurt with a swirl of honey and crunchy walnuts — indulgent yet nutritious.',
    calories: 230,
    protein: 14,
    carbs: 18,
    fat: 10,
    fiber: 1,
    ingredients: ['150g Greek yogurt', '1 tbsp honey', '15g walnuts, chopped'],
    preparation: 'Spoon yogurt into a bowl. Drizzle honey over the top and scatter walnuts.',
    excludeFor: ['vegan', 'dairy_free', 'nut_free'],
  },
  {
    id: 's5',
    name: 'Hard-Boiled Eggs with Everything Seasoning',
    type: 'snack',
    description: 'Protein-packed hard-boiled eggs dusted with everything bagel seasoning — simple and filling.',
    calories: 150,
    protein: 12,
    carbs: 2,
    fat: 10,
    fiber: 0,
    ingredients: ['2 eggs', '1 tsp everything bagel seasoning', 'Salt'],
    preparation: 'Boil eggs 10 min, cool in ice water, peel. Halve and sprinkle with everything seasoning.',
    excludeFor: ['vegan'],
  },
  {
    id: 's6',
    name: 'Edamame with Sea Salt',
    type: 'snack',
    description: 'Steamed edamame pods with flaky sea salt — rich in plant protein and fun to eat.',
    calories: 160,
    protein: 12,
    carbs: 12,
    fat: 5,
    fiber: 5,
    ingredients: ['1 cup edamame (in pods)', 'Flaky sea salt'],
    preparation: 'Boil or microwave edamame 3–5 min until tender. Drain and toss with sea salt.',
    excludeFor: [],
  },
  {
    id: 's7',
    name: 'Cucumber Rounds with Tzatziki',
    type: 'snack',
    description: 'Cool cucumber slices with homemade tzatziki — refreshing and low-calorie.',
    calories: 120,
    protein: 5,
    carbs: 8,
    fat: 7,
    fiber: 1,
    ingredients: ['1 cucumber', '80g Greek yogurt', '½ garlic clove', '1 tbsp olive oil', 'Fresh mint', 'Salt'],
    preparation: 'Slice cucumber into rounds. Mix yogurt with grated garlic, oil, salt and mint. Serve as a dip.',
    excludeFor: ['vegan', 'dairy_free'],
  },
  {
    id: 's8',
    name: 'Sliced Turkey & Avocado Roll-Ups',
    type: 'snack',
    description: 'Thin turkey slices rolled around avocado and rocket — a no-carb, high-protein bite.',
    calories: 180,
    protein: 16,
    carbs: 5,
    fat: 11,
    fiber: 3,
    ingredients: ['80g sliced turkey breast', '½ avocado, sliced', 'Handful of rocket', 'Lemon juice', 'Salt & pepper'],
    preparation: 'Lay turkey slices flat. Place avocado and rocket at one end. Season with lemon and salt. Roll up tightly and secure with a toothpick.',
    excludeFor: ['vegetarian', 'vegan'],
  },
  {
    id: 's9',
    name: 'Berries & Cottage Cheese',
    type: 'snack',
    description: 'Fresh berries stirred into creamy cottage cheese — protein-rich, refreshing and satisfying.',
    calories: 160,
    protein: 14,
    carbs: 14,
    fat: 3,
    fiber: 2,
    ingredients: ['150g cottage cheese', '½ cup mixed berries', '1 tsp vanilla extract'],
    preparation: 'Combine cottage cheese with vanilla. Top with fresh berries.',
    excludeFor: ['vegan', 'dairy_free'],
  },
  {
    id: 's10',
    name: 'Dark Chocolate & Almonds',
    type: 'snack',
    description: 'A square of dark chocolate with a small handful of almonds — antioxidant-rich and satisfying.',
    calories: 210,
    protein: 5,
    carbs: 16,
    fat: 14,
    fiber: 3,
    ingredients: ['20g dark chocolate (70%+)', '20g raw almonds'],
    preparation: 'Break chocolate into squares. Pair with almonds for a balanced sweet-savoury snack.',
    excludeFor: ['nut_free'],
  },

  // ─── KID-FRIENDLY BREAKFAST ───────────────────────────────────────────────
  {
    id: 'kb1',
    name: 'Banana Pancakes with Maple Syrup',
    type: 'breakfast',
    description: 'Fluffy golden pancakes topped with sliced bananas and a drizzle of maple syrup — a breakfast kids absolutely love.',
    calories: 340,
    protein: 9,
    carbs: 60,
    fat: 8,
    fiber: 3,
    ingredients: ['1 cup plain flour', '1 tbsp sugar', '1 tsp baking powder', '1 egg', '¾ cup milk', '1 tbsp melted butter', '1 banana, sliced', '2 tbsp maple syrup'],
    preparation: 'Mix flour, sugar and baking powder. Whisk in egg and milk to make a smooth batter. Melt butter in a non-stick pan, pour in spoonfuls of batter and cook 2 min per side until golden. Top with banana slices and maple syrup.',
    excludeFor: ['vegan', 'dairy_free', 'gluten_free', 'no_bread'],
    kidFriendly: true,
  },
  {
    id: 'kb2',
    name: 'Peanut Butter Toast with Banana',
    type: 'breakfast',
    description: 'Thick wholegrain toast spread with creamy peanut butter and topped with banana slices and a drizzle of honey.',
    calories: 290,
    protein: 10,
    carbs: 40,
    fat: 12,
    fiber: 5,
    ingredients: ['2 slices wholegrain bread', '2 tbsp peanut butter', '1 banana, sliced', '1 tsp honey'],
    preparation: 'Toast the bread until golden and crispy. Spread generously with peanut butter. Arrange banana slices on top and drizzle with honey.',
    excludeFor: ['vegan', 'gluten_free', 'no_bread', 'nut_free'],
    kidFriendly: true,
  },
  {
    id: 'kb3',
    name: 'Cheesy Scrambled Eggs',
    type: 'breakfast',
    description: 'Soft, creamy scrambled eggs loaded with melted cheddar — simple, tasty and packed with protein for growing kids.',
    calories: 310,
    protein: 22,
    carbs: 4,
    fat: 22,
    fiber: 0,
    ingredients: ['3 eggs', '2 tbsp milk', '30g cheddar cheese, grated', '1 tbsp butter', 'Salt & pepper', 'Ketchup to serve'],
    preparation: 'Whisk eggs with milk, salt and pepper. Melt butter in a pan over low heat. Add eggs and fold slowly with a spatula until barely set. Stir in cheddar and remove from heat immediately. Serve with a side of ketchup.',
    excludeFor: ['vegan', 'dairy_free'],
    kidFriendly: true,
  },
  {
    id: 'kb4',
    name: 'Oatmeal with Berries and Honey',
    type: 'breakfast',
    description: 'Warm, creamy oatmeal topped with mixed berries and a swirl of honey — a cosy and nutritious start to the morning.',
    calories: 280,
    protein: 7,
    carbs: 50,
    fat: 5,
    fiber: 5,
    ingredients: ['½ cup rolled oats', '1 cup milk', '½ cup mixed berries', '1 tbsp honey', 'Pinch of cinnamon'],
    preparation: 'Heat oats and milk in a saucepan over medium heat, stirring until thick and creamy (about 5 min). Pour into a bowl, top with berries, drizzle honey and dust with cinnamon.',
    excludeFor: ['vegan', 'dairy_free', 'low_carb'],
    kidFriendly: true,
  },
  {
    id: 'kb5',
    name: 'Strawberry Banana Smoothie Bowl',
    type: 'breakfast',
    description: 'A thick blended smoothie bowl of frozen banana and strawberries, topped with granola and fresh fruit — colourful and fun to eat.',
    calories: 250,
    protein: 6,
    carbs: 46,
    fat: 4,
    fiber: 5,
    ingredients: ['1 frozen banana', '½ cup strawberries', '½ cup milk', '2 tbsp granola', '1 tbsp honey', 'Fresh fruit to decorate'],
    preparation: 'Blend frozen banana, strawberries and milk until thick and smooth — it should be spoonable, not drinkable. Pour into a bowl, top with granola, fresh fruit and a drizzle of honey.',
    excludeFor: ['vegan', 'dairy_free', 'low_carb'],
    kidFriendly: true,
  },
  {
    id: 'kb6',
    name: 'Cinnamon French Toast',
    type: 'breakfast',
    description: 'Thick slices of bread soaked in cinnamon egg custard and pan-fried until golden — serve with maple syrup for a treat kids go wild for.',
    calories: 320,
    protein: 12,
    carbs: 42,
    fat: 10,
    fiber: 2,
    ingredients: ['2 thick slices of bread', '2 eggs', '¼ cup milk', '1 tsp cinnamon', '1 tbsp butter', '2 tbsp maple syrup', 'Icing sugar to dust (optional)'],
    preparation: 'Whisk together eggs, milk and cinnamon in a shallow bowl. Dip each bread slice and coat well on both sides. Melt butter in a pan over medium heat and cook bread 2–3 min per side until golden. Serve with maple syrup and a dusting of icing sugar.',
    excludeFor: ['vegan', 'dairy_free', 'gluten_free', 'no_bread'],
    kidFriendly: true,
  },

  // ─── KID-FRIENDLY LUNCH ───────────────────────────────────────────────────
  {
    id: 'kl1',
    name: 'Cheesy Pasta with Hidden Vegetables',
    type: 'lunch',
    description: 'Creamy cheese sauce over pasta with carrots and peas sneaked in — kids will love every bite without even noticing the veg.',
    calories: 390,
    protein: 15,
    carbs: 58,
    fat: 13,
    fiber: 4,
    ingredients: ['200g pasta (any shape)', '80g cheddar cheese, grated', '½ cup frozen peas', '1 carrot, finely grated', '2 tbsp butter', '2 tbsp plain flour', '1½ cups milk', 'Salt & pepper'],
    preparation: 'Cook pasta per packet instructions, adding peas in the last 2 min. Make cheese sauce: melt butter, stir in flour, gradually add milk stirring until smooth and thick (5 min). Add cheese and season. Drain pasta with peas, stir in grated carrot and coat with cheese sauce.',
    excludeFor: ['vegan', 'dairy_free', 'gluten_free', 'no_bread'],
    kidFriendly: true,
  },
  {
    id: 'kl2',
    name: 'Grilled Cheese with Tomato Soup',
    type: 'lunch',
    description: 'Golden grilled cheese sandwiches alongside warm tomato soup — a classic combo kids never tire of.',
    calories: 370,
    protein: 14,
    carbs: 46,
    fat: 15,
    fiber: 4,
    ingredients: ['2 slices bread', '60g cheddar cheese, sliced', '1 tbsp butter', '400ml tomato soup', 'Pinch of sugar', 'Fresh basil (optional)'],
    preparation: 'Heat soup in a pan with a pinch of sugar. Butter the outside of each bread slice. Fill with cheese, press together. Cook in a dry pan 2–3 min per side until golden and cheese is melted. Slice diagonally and serve alongside warm soup.',
    excludeFor: ['vegan', 'dairy_free', 'gluten_free', 'no_bread'],
    kidFriendly: true,
  },
  {
    id: 'kl3',
    name: 'Chicken Noodle Soup',
    type: 'lunch',
    description: 'Comforting homemade chicken noodle soup with tender chicken, sweet carrots and soft noodles — a hug in a bowl.',
    calories: 300,
    protein: 22,
    carbs: 36,
    fat: 5,
    fiber: 3,
    ingredients: ['150g chicken breast', '1 cup egg noodles', '2 carrots, sliced', '2 celery stalks, sliced', '1 small onion, diced', '1 litre chicken stock', '2 garlic cloves', 'Fresh parsley', 'Salt & pepper'],
    preparation: 'Bring stock to a simmer with onion, carrot, celery and garlic. Add whole chicken breast and poach 15 min. Remove chicken, shred with two forks and return to pot. Add noodles and cook 8 min until tender. Season and garnish with parsley.',
    excludeFor: ['vegetarian', 'vegan', 'gluten_free'],
    kidFriendly: true,
  },
  {
    id: 'kl4',
    name: 'PB&J Sandwich with Apple Slices',
    type: 'lunch',
    description: 'The classic peanut butter and jam sandwich on wholegrain bread, served with cinnamon apple slices on the side.',
    calories: 360,
    protein: 11,
    carbs: 52,
    fat: 14,
    fiber: 6,
    ingredients: ['2 slices wholegrain bread', '2 tbsp peanut butter', '1 tbsp strawberry jam', '1 apple, sliced', 'Pinch of cinnamon'],
    preparation: 'Spread one bread slice generously with peanut butter and the other with jam. Press together and slice diagonally. Dust apple slices with cinnamon and arrange on the side.',
    excludeFor: ['gluten_free', 'no_bread', 'nut_free'],
    kidFriendly: true,
  },
  {
    id: 'kl5',
    name: 'Mini Cheese Pizzas',
    type: 'lunch',
    description: 'Personal-sized pizzas on pitta bases with tomato sauce and melted mozzarella — let kids choose their own toppings!',
    calories: 370,
    protein: 15,
    carbs: 50,
    fat: 12,
    fiber: 3,
    ingredients: ['2 small pitta breads', '4 tbsp tomato sauce', '80g mozzarella, grated', 'Dried oregano', '4 cherry tomatoes, halved', 'Optional: sweetcorn, sliced peppers'],
    preparation: 'Preheat oven to 200 °C. Spread tomato sauce on each pitta bread. Top with mozzarella, cherry tomatoes and any chosen toppings. Sprinkle oregano. Bake 8–10 min until cheese is bubbling and golden.',
    excludeFor: ['vegan', 'dairy_free', 'gluten_free', 'no_bread'],
    kidFriendly: true,
  },
  {
    id: 'kl6',
    name: 'Veggie Quesadillas with Salsa',
    type: 'lunch',
    description: 'Crispy flour tortillas filled with melted cheese, sweet peppers and corn — fun to make and even more fun to eat.',
    calories: 350,
    protein: 12,
    carbs: 44,
    fat: 13,
    fiber: 5,
    ingredients: ['2 flour tortillas', '80g cheddar cheese, grated', '½ red bell pepper, diced', '½ cup sweetcorn', '2 tbsp mild salsa', 'Small handful of baby spinach'],
    preparation: 'Place one tortilla in a dry pan over medium heat. Sprinkle cheese over half, add peppers, corn and spinach. Fold tortilla over. Cook 2–3 min per side until crispy and cheese is melted. Cut into wedges and serve with salsa for dipping.',
    excludeFor: ['vegan', 'dairy_free', 'gluten_free', 'no_bread'],
    kidFriendly: true,
  },

  // ─── KID-FRIENDLY DINNER ──────────────────────────────────────────────────
  {
    id: 'kd1',
    name: 'Spaghetti with Simple Tomato Sauce',
    type: 'dinner',
    description: 'Spaghetti tossed in a rich homemade tomato sauce — an all-time kid favourite that never fails to please.',
    calories: 410,
    protein: 13,
    carbs: 70,
    fat: 9,
    fiber: 6,
    ingredients: ['200g spaghetti', '400g passata', '1 onion, diced', '2 garlic cloves, minced', '1 tbsp olive oil', '1 tsp dried oregano', '1 tsp sugar', 'Salt & pepper', 'Grated parmesan to serve (optional)'],
    preparation: 'Cook spaghetti per packet instructions. Sauté onion in olive oil 5 min until soft. Add garlic, cook 1 min. Add passata, oregano, sugar and season. Simmer 10 min. Toss with drained spaghetti and serve with grated parmesan.',
    excludeFor: ['gluten_free', 'no_bread', 'low_carb'],
    kidFriendly: true,
  },
  {
    id: 'kd2',
    name: 'Baked Chicken Strips with Sweet Potato Fries',
    type: 'dinner',
    description: 'Crispy oven-baked chicken strips alongside golden sweet potato fries — a healthier take on kids\' favourite comfort food.',
    calories: 430,
    protein: 36,
    carbs: 44,
    fat: 10,
    fiber: 5,
    ingredients: ['200g chicken breast, cut into strips', '1 large sweet potato, cut into fries', '2 tbsp olive oil', '1 tsp paprika', '½ tsp garlic powder', '½ cup breadcrumbs', '1 egg, beaten', 'Salt & pepper', 'Ketchup to serve'],
    preparation: 'Preheat oven to 220 °C. Toss sweet potato fries with 1 tbsp oil, paprika and salt. Roast 25 min, turning once. Dip chicken strips in beaten egg then breadcrumbs. Bake on a greased tray with remaining oil for 15–18 min until golden and cooked through. Serve with ketchup.',
    excludeFor: ['vegetarian', 'vegan', 'gluten_free'],
    kidFriendly: true,
  },
  {
    id: 'kd3',
    name: 'Fish Fingers with Peas and Mash',
    type: 'dinner',
    description: 'Homemade breaded fish fingers with fluffy mashed potato and peas — a British classic that kids request again and again.',
    calories: 400,
    protein: 28,
    carbs: 46,
    fat: 12,
    fiber: 5,
    ingredients: ['200g white fish fillet (cod or haddock)', '½ cup breadcrumbs', '1 egg, beaten', '2 large potatoes', '2 tbsp butter', '¼ cup milk', '1 cup frozen peas', 'Salt & pepper', 'Ketchup to serve'],
    preparation: 'Boil potatoes 15 min, drain, mash with butter, milk and salt. Boil peas. Cut fish into finger shapes, dip in beaten egg then breadcrumbs. Bake at 200 °C for 15 min until golden and crispy. Serve with mash, peas and ketchup.',
    excludeFor: ['vegetarian', 'vegan', 'dairy_free', 'gluten_free'],
    kidFriendly: true,
  },
  {
    id: 'kd4',
    name: 'Cheesy Pasta Bake',
    type: 'dinner',
    description: 'Pasta baked in a bubbling cheese sauce with a golden breadcrumb topping — comfort food that the whole family will love.',
    calories: 440,
    protein: 18,
    carbs: 58,
    fat: 16,
    fiber: 3,
    ingredients: ['200g penne pasta', '100g cheddar cheese, grated', '50g mozzarella, grated', '1½ cups milk', '2 tbsp butter', '2 tbsp plain flour', '½ cup breadcrumbs', 'Paprika', 'Salt & pepper'],
    preparation: 'Cook pasta. Make cheese sauce: melt butter, whisk in flour, gradually add milk stirring until thick (5 min). Add ¾ of cheddar and season. Mix sauce with pasta, pour into baking dish. Top with remaining cheeses and breadcrumbs, dust with paprika. Bake 200 °C for 20 min until golden and bubbling.',
    excludeFor: ['vegan', 'dairy_free', 'gluten_free', 'no_bread'],
    kidFriendly: true,
  },
  {
    id: 'kd5',
    name: 'Mini Beef Tacos',
    type: 'dinner',
    description: 'Soft taco shells filled with seasoned ground beef, shredded lettuce, cheese and mild salsa — a fun, build-your-own dinner kids love.',
    calories: 420,
    protein: 24,
    carbs: 44,
    fat: 16,
    fiber: 5,
    ingredients: ['150g lean ground beef', '6 small taco shells', '½ cup shredded iceberg lettuce', '1 tomato, diced', '40g mild cheddar cheese, grated', '2 tbsp mild salsa', '1 tsp cumin', '½ tsp mild paprika', '2 tbsp soured cream'],
    preparation: 'Brown ground beef in a pan, drain any excess fat. Add cumin and paprika, stir and cook 2 min. Warm taco shells as per packet instructions. Set out all the fillings and let kids assemble their own tacos.',
    excludeFor: ['vegetarian', 'vegan', 'dairy_free', 'gluten_free'],
    kidFriendly: true,
  },
  {
    id: 'kd6',
    name: 'Egg Fried Rice with Vegetables',
    type: 'dinner',
    description: 'Fluffy fried rice with scrambled eggs, peas, sweetcorn and a splash of soy sauce — quick, easy and always a hit.',
    calories: 370,
    protein: 12,
    carbs: 56,
    fat: 10,
    fiber: 4,
    ingredients: ['1 cup cooked rice (day-old is best)', '2 eggs', '½ cup frozen peas', '½ cup sweetcorn', '2 spring onions, sliced', '2 tbsp soy sauce', '1 tbsp sesame oil', '1 tbsp vegetable oil', '1 tsp ginger, grated'],
    preparation: 'Heat oil in a wok or large pan over high heat. Add ginger, stir 30 sec. Push to one side and scramble eggs in the pan. Add rice, breaking up any clumps. Stir in peas, corn and spring onions. Add soy sauce and toss everything together. Drizzle sesame oil and serve.',
    excludeFor: ['vegan', 'low_carb'],
    kidFriendly: true,
  },

  // ─── KID-FRIENDLY SNACKS ──────────────────────────────────────────────────
  {
    id: 'ks1',
    name: 'Apple Slices with Peanut Butter Dip',
    type: 'snack',
    description: 'Crisp apple slices with a pot of creamy peanut butter for dipping — sweet, satisfying and full of energy.',
    calories: 190,
    protein: 5,
    carbs: 26,
    fat: 8,
    fiber: 4,
    ingredients: ['1 medium apple, sliced', '2 tbsp peanut butter', 'Cinnamon to dust (optional)'],
    preparation: 'Core and slice the apple into wedges. Arrange on a plate with a small pot of peanut butter for dipping. Dust lightly with cinnamon if desired.',
    excludeFor: ['nut_free'],
    kidFriendly: true,
  },
  {
    id: 'ks2',
    name: 'Cheese and Crackers with Cherry Tomatoes',
    type: 'snack',
    description: 'Mild cheddar cubes with whole-grain crackers and sweet cherry tomatoes — a simple snack board kids can help assemble.',
    calories: 170,
    protein: 7,
    carbs: 18,
    fat: 8,
    fiber: 1,
    ingredients: ['40g mild cheddar cheese, sliced or cubed', '8 whole-grain crackers', '6 cherry tomatoes', 'Small handful of grapes (optional)'],
    preparation: 'Arrange crackers, cheese cubes and cherry tomatoes on a small plate. Mix and match for a fun snack board — no cooking needed!',
    excludeFor: ['vegan', 'dairy_free', 'gluten_free'],
    kidFriendly: true,
  },
  {
    id: 'ks3',
    name: 'Rainbow Fruit Skewers',
    type: 'snack',
    description: 'Colourful fruit threaded onto skewers in rainbow order — a fun, zero-prep snack that makes eating fruit an adventure.',
    calories: 110,
    protein: 1,
    carbs: 26,
    fat: 0,
    fiber: 3,
    ingredients: ['½ cup strawberries', '½ cup melon, cubed', '½ cup grapes', '¼ cup blueberries', '¼ cup pineapple chunks', 'Wooden skewers'],
    preparation: 'Thread fruit onto skewers in rainbow colour order — red strawberries, orange melon, green grapes, blue blueberries, yellow pineapple. Serve as-is or with a small pot of yogurt for dipping.',
    excludeFor: [],
    kidFriendly: true,
  },
  {
    id: 'ks4',
    name: 'Yogurt with Berries and Granola',
    type: 'snack',
    description: 'Creamy vanilla yogurt layered with mixed berries and crunchy granola — healthy enough for a snack, delicious enough for dessert.',
    calories: 180,
    protein: 8,
    carbs: 26,
    fat: 4,
    fiber: 2,
    ingredients: ['150g vanilla yogurt', '½ cup mixed berries', '2 tbsp granola', '1 tsp honey'],
    preparation: 'Spoon yogurt into a bowl or cup. Top with mixed berries and sprinkle granola over. Drizzle with a little honey. Layer in a glass for a fun parfait presentation!',
    excludeFor: ['vegan', 'dairy_free'],
    kidFriendly: true,
  },
  {
    id: 'ks5',
    name: 'Banana Oat Energy Bites',
    type: 'snack',
    description: 'No-bake bite-sized snacks made from banana, oats and honey — naturally sweet, filling and easy to make together with kids.',
    calories: 140,
    protein: 3,
    carbs: 26,
    fat: 3,
    fiber: 3,
    ingredients: ['1 ripe banana', '½ cup rolled oats', '1 tbsp honey', '½ tsp cinnamon', '1 tbsp mini chocolate chips (optional)'],
    preparation: 'Mash banana thoroughly with a fork. Mix in oats, honey, cinnamon and chocolate chips if using. Roll into small balls and place on a lined tray. Refrigerate 30 min until firm. Makes about 8 bites.',
    excludeFor: ['vegan', 'low_carb'],
    kidFriendly: true,
  },
  {
    id: 'ks6',
    name: 'Veggie Sticks with Hummus',
    type: 'snack',
    description: 'Crunchy carrot, cucumber and celery sticks with a pot of creamy hummus — colourful, fun to dip and good for everyone.',
    calories: 130,
    protein: 4,
    carbs: 16,
    fat: 6,
    fiber: 4,
    ingredients: ['2 carrots, cut into sticks', '1 cucumber, sliced into rounds', '1 celery stalk, cut into sticks', '4 tbsp hummus', 'Paprika to sprinkle'],
    preparation: 'Arrange colourful veggie sticks around a small bowl of hummus. Dust hummus with a pinch of paprika for colour. Encourage kids to dip and crunch!',
    excludeFor: [],
    kidFriendly: true,
  },
];

export const motivationalMessages: string[] = [
  'Every nutritious meal is a step towards the healthiest version of you. Keep it up!',
  'You are what you eat — so today, choose to be vibrant, strong and energised!',
  'Small consistent choices add up to big results. Today\'s meal plan is your foundation.',
  'Nourishing your body is an act of self-love. You deserve to feel great!',
  'Progress is progress, no matter how small. Celebrating your healthy choices matters.',
  'Your body is your most valuable asset — fuel it with care and intention today.',
  'Healthy eating isn\'t a diet, it\'s a lifestyle. You\'re building something that lasts.',
  'Each meal you plan is a commitment to your wellbeing. That\'s something to be proud of.',
  'The best time to eat well was yesterday — the second best time is right now!',
  'Consistency beats perfection every time. Keep showing up for yourself.',
  'You have the power to transform your health one meal at a time. Let\'s do this!',
  'Real food, real results. Your body will thank you for every healthy bite.',
  'Think of healthy eating as a gift to your future self. Unwrap it every day.',
  'You don\'t have to eat less — you just have to eat right. Today\'s plan has you covered.',
  'Energy, clarity, confidence — all on your plate. Enjoy today\'s meals!',
  'Meal by meal, day by day, you\'re creating a healthier you. That\'s remarkable.',
  'Greatness is built in the small moments. Like choosing a nutritious breakfast.',
  'Your commitment to healthy eating inspires those around you. Keep leading by example.',
  'Fuelling your body well isn\'t just about weight — it\'s about living fully.',
  'Today is a new opportunity to nourish yourself. Make the most of it!',
];

export const childMessages: string[] = [
  'Great job eating healthy today — your body loves all those good foods!',
  'You are a superstar for choosing nutritious meals. Keep it up!',
  'Every healthy meal makes you stronger, faster and smarter. Amazing!',
  'Today\'s meals are packed with goodness to help you grow big and strong!',
  'Eating well is like giving your body a superpower. You\'re doing great!',
  'Fruits and veggies give you energy to play, run and have lots of fun!',
  'You\'re making brilliant choices today — your body will thank you for it!',
  'Healthy food is fuel for all your adventures. Let\'s go!',
  'Eating a rainbow of colours means lots of vitamins for a healthy you!',
  'Growing up healthy starts one meal at a time — you\'re doing brilliantly!',
];
